stages:
  prepare:
    cmd: python scripts/prepare_data.py
    outs:
      - data/processed

  train:
    cmd: python scripts/train.py
    deps:
      - data/processed
    outs:
      - models/trained_model.pt
    metrics:
      - metrics.json
