name: MLOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc

  train:
    runs-on: ubuntu-latest
    needs: setup
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc[s3]  # S3 remote kullanımı için

    - name: Configure DVC remote (if needed)
      run: dvc remote default myremote

    - name: Pull data from DVC
      run: dvc pull

    - name: Run training script
      run: |
        python src/train.py
        dvc add models/model.pkl models/vectorizer.pkl
        git add models/*.dvc
        git commit -m "Track trained model with DVC" || echo "No changes to commit"
        dvc push
        
  evaluate:
    runs-on: ubuntu-latest
    needs: train

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc[s3]

    - name: Pull model/data from DVC
      run: dvc pull

    - name: Run evaluation script
      run: python src/evaluate.py
  test:
    runs-on: ubuntu-latest
    needs: evaluate

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc[s3]

    - name: Pull model/data from DVC
      run: dvc pull

    - name: Run testing script
      run: python src/test.py
  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc[s3]

    - name: Pull model/data from DVC
      run: dvc pull

    - name: Generate report
      run: python src/report.py
