name: MLOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # requirements.txt içindeki bağımlılıkları yükle
        pip install dvc  # DVC'yi ayrıca yükle

  train:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Tekrar requirements.txt yükleniyor
        pip install dvc  # DVC'yi ayrıca yükle

    - name: Run training script
      run: |
        python src/train.py
        dvc push  # Model ve veriyi DVC'ye yükle
