  train:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install -r requirements.txt
        pip install dvc

    - name: Run training script
      run: |
        python src/train.py
        dvc push  # Push model and data

