  train:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up DVC
      run: |
        pip install dvc
        dvc pull  # Verileri DVC sunucusundan çek

    - name: Run training script
      run: |
        python src/train.py  # `train.py` dosyasını `src` dizininden çalıştır
        dvc push  # Model ve vektörleştiriciyi DVC'ye yükle

